#!/usr/bin/env ruby

require 'rexml/document'

include REXML

plist_path = ARGV[0]

doc = Document.new(File.new(plist_path))
args_array_element = REXML::XPath.first(doc, "plist/dict/key[text()='ProgramArguments']/following-sibling::array")
text_args = XPath.match(args_array_element, 'string').map {|e| e.text }

puts text_args.join(" ")
